"""baseline_initial_schema

Revision ID: 2f3ac63f4728
Revises: 
Create Date: 2026-05-10 13:13:15.783510

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3ac63f4728'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_constant_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("node_type IN ('root','grade','subject','theme')", name='ck_curriculum_constant_nodes_node_type'),
    sa.CheckConstraint('depth >= 0', name='ck_curriculum_constant_nodes_depth_non_negative'),
    sa.ForeignKeyConstraint(['parent_id'], ['curriculum_constant_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'slug', name='uq_curriculum_constant_nodes_parent_slug'),
    sa.UniqueConstraint('path', name='uq_curriculum_constant_nodes_path')
    )
    op.create_index('ix_curriculum_constant_nodes_node_type', 'curriculum_constant_nodes', ['node_type'], unique=False)
    op.create_index('ix_curriculum_constant_nodes_parent_id', 'curriculum_constant_nodes', ['parent_id'], unique=False)
    op.create_index('ix_curriculum_constant_nodes_path', 'curriculum_constant_nodes', ['path'], unique=False)
    op.create_table('curriculum_folder_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("node_type IN ('folder')", name='ck_curriculum_folder_nodes_node_type'),
    sa.CheckConstraint('depth >= 0', name='ck_curriculum_folder_nodes_depth_non_negative'),
    sa.ForeignKeyConstraint(['parent_id'], ['curriculum_folder_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'slug', name='uq_curriculum_folder_nodes_parent_slug'),
    sa.UniqueConstraint('path', name='uq_curriculum_folder_nodes_path')
    )
    op.create_index('ix_curriculum_folder_nodes_grade', 'curriculum_folder_nodes', ['grade'], unique=False)
    op.create_index('ix_curriculum_folder_nodes_parent_id', 'curriculum_folder_nodes', ['parent_id'], unique=False)
    op.create_index('ix_curriculum_folder_nodes_path', 'curriculum_folder_nodes', ['path'], unique=False)
    op.create_index('ix_curriculum_folder_nodes_subject', 'curriculum_folder_nodes', ['subject'], unique=False)
    op.create_index('ix_curriculum_folder_nodes_theme', 'curriculum_folder_nodes', ['theme'], unique=False)
    op.create_table('legacy_yaml_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('yaml_path', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('geometry','turkce')", name='ck_legacy_yaml_instances_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'yaml_path', name='uq_legacy_yaml_instances_kind_path')
    )
    op.create_index('ix_legacy_yaml_instances_kind', 'legacy_yaml_instances', ['kind'], unique=False)
    op.create_table('property_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('defined_at_curriculum_node_id', sa.Text(), nullable=False),
    sa.Column('parent_property_id', sa.String(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_key', sa.Text(), nullable=False),
    sa.Column('canonical_path', sa.Text(), nullable=False),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('constraints_json', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("data_type IN ('text','bool','number','json','array','enum','object')", name='ck_property_definitions_data_type'),
    sa.ForeignKeyConstraint(['parent_property_id'], ['property_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defined_at_curriculum_node_id', 'canonical_path', name='uq_property_definitions_curriculum_node_path')
    )
    op.create_index('ix_property_definitions_canonical_path', 'property_definitions', ['canonical_path'], unique=False)
    op.create_index('ix_property_definitions_defined_at_curriculum_node_id', 'property_definitions', ['defined_at_curriculum_node_id'], unique=False)
    op.create_index('ix_property_definitions_parent_property_id', 'property_definitions', ['parent_property_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('variant_rotation_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('yaml_key', sa.Text(), nullable=False),
    sa.Column('last_index', sa.Integer(), nullable=False),
    sa.Column('last_variant', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_rotation_states_yaml_key'), 'variant_rotation_states', ['yaml_key'], unique=True)
    op.create_table('auth_tokens',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('yaml_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('curriculum_folder_node_id', sa.String(), nullable=False),
    sa.Column('template_code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_schema_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_yaml_templates_status'),
    sa.ForeignKeyConstraint(['curriculum_folder_node_id'], ['curriculum_folder_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code', name='uq_yaml_templates_template_code')
    )
    op.create_index('ix_yaml_templates_curriculum_folder_node_id', 'yaml_templates', ['curriculum_folder_node_id'], unique=False)
    op.create_index('ix_yaml_templates_status', 'yaml_templates', ['status'], unique=False)
    op.create_table('yaml_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('instance_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('values_json', sa.Text(), nullable=False),
    sa.Column('rendered_yaml_text', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','final','archived')", name='ck_yaml_instances_status'),
    sa.ForeignKeyConstraint(['template_id'], ['yaml_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_yaml_instances_status', 'yaml_instances', ['status'], unique=False)
    op.create_index('ix_yaml_instances_template_id', 'yaml_instances', ['template_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('yaml_filename', sa.String(), nullable=False),
    sa.Column('yaml_instance_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_config_json', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['yaml_instance_id'], ['yaml_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yaml_instance_property_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('property_definition_id', sa.String(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['yaml_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_definition_id'], ['property_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'property_definition_id', name='uq_yaml_instance_property_values_pair')
    )
    op.create_index('ix_yaml_instance_property_values_instance_id', 'yaml_instance_property_values', ['instance_id'], unique=False)
    op.create_table('yaml_variant_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_instance_id', sa.String(), nullable=False),
    sa.Column('to_instance_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("relation_type IN ('clone','variant','derived','merge')", name='ck_yaml_variant_relationships_type'),
    sa.CheckConstraint('from_instance_id <> to_instance_id', name='ck_yaml_variant_relationships_no_self'),
    sa.ForeignKeyConstraint(['from_instance_id'], ['yaml_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_instance_id'], ['yaml_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_instance_id', 'to_instance_id', 'relation_type', name='uq_yaml_variant_relationships_edge_type')
    )
    op.create_index('ix_yaml_variant_relationships_from_instance_id', 'yaml_variant_relationships', ['from_instance_id'], unique=False)
    op.create_index('ix_yaml_variant_relationships_to_instance_id', 'yaml_variant_relationships', ['to_instance_id'], unique=False)
    op.create_table('sub_pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_composite_image_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_layout_html_validation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_main_html_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_main_layout_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_main_question_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_question_layout_validation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_rule_evaluation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_rule_extraction_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('object_bucket', sa.Text(), nullable=True),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('source_pipeline_id', sa.String(), nullable=True),
    sa.Column('source_sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('source_agent_name', sa.Text(), nullable=True),
    sa.Column('source_agent_run_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('yaml_rendered','question','layout','html','generated_asset','catalog_asset','rendered_image')", name='ck_artifacts_kind'),
    sa.ForeignKeyConstraint(['source_pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['source_sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_is_favorite', 'artifacts', ['is_favorite'], unique=False)
    op.create_index('ix_artifacts_kind', 'artifacts', ['kind'], unique=False)
    op.create_index('ix_artifacts_source_pipeline_id', 'artifacts', ['source_pipeline_id'], unique=False)
    op.create_index('ix_artifacts_source_sub_pipeline_id', 'artifacts', ['source_sub_pipeline_id'], unique=False)
    op.create_table('favorite_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('source_sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_agent_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_table', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stored_json_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('source_sub_pipeline_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_sub_pipeline_id'], ['sub_pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'filename', name='uq_stored_json_outputs_kind_filename')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_json_outputs')
    op.drop_table('pipeline_logs')
    op.drop_table('pipeline_agent_links')
    op.drop_table('favorite_outputs')
    op.drop_index('ix_artifacts_source_sub_pipeline_id', table_name='artifacts')
    op.drop_index('ix_artifacts_source_pipeline_id', table_name='artifacts')
    op.drop_index('ix_artifacts_kind', table_name='artifacts')
    op.drop_index('ix_artifacts_is_favorite', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('agent_rule_extraction_runs')
    op.drop_table('agent_rule_evaluation_runs')
    op.drop_table('agent_question_layout_validation_runs')
    op.drop_table('agent_main_question_runs')
    op.drop_table('agent_main_layout_runs')
    op.drop_table('agent_main_html_runs')
    op.drop_table('agent_layout_html_validation_runs')
    op.drop_table('agent_composite_image_runs')
    op.drop_table('sub_pipeline_runs')
    op.drop_index('ix_yaml_variant_relationships_to_instance_id', table_name='yaml_variant_relationships')
    op.drop_index('ix_yaml_variant_relationships_from_instance_id', table_name='yaml_variant_relationships')
    op.drop_table('yaml_variant_relationships')
    op.drop_index('ix_yaml_instance_property_values_instance_id', table_name='yaml_instance_property_values')
    op.drop_table('yaml_instance_property_values')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_yaml_instances_template_id', table_name='yaml_instances')
    op.drop_index('ix_yaml_instances_status', table_name='yaml_instances')
    op.drop_table('yaml_instances')
    op.drop_index('ix_yaml_templates_status', table_name='yaml_templates')
    op.drop_index('ix_yaml_templates_curriculum_folder_node_id', table_name='yaml_templates')
    op.drop_table('yaml_templates')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_variant_rotation_states_yaml_key'), table_name='variant_rotation_states')
    op.drop_table('variant_rotation_states')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_property_definitions_parent_property_id', table_name='property_definitions')
    op.drop_index('ix_property_definitions_defined_at_curriculum_node_id', table_name='property_definitions')
    op.drop_index('ix_property_definitions_canonical_path', table_name='property_definitions')
    op.drop_table('property_definitions')
    op.drop_index('ix_legacy_yaml_instances_kind', table_name='legacy_yaml_instances')
    op.drop_table('legacy_yaml_instances')
    op.drop_index('ix_curriculum_folder_nodes_theme', table_name='curriculum_folder_nodes')
    op.drop_index('ix_curriculum_folder_nodes_subject', table_name='curriculum_folder_nodes')
    op.drop_index('ix_curriculum_folder_nodes_path', table_name='curriculum_folder_nodes')
    op.drop_index('ix_curriculum_folder_nodes_parent_id', table_name='curriculum_folder_nodes')
    op.drop_index('ix_curriculum_folder_nodes_grade', table_name='curriculum_folder_nodes')
    op.drop_table('curriculum_folder_nodes')
    op.drop_index('ix_curriculum_constant_nodes_path', table_name='curriculum_constant_nodes')
    op.drop_index('ix_curriculum_constant_nodes_parent_id', table_name='curriculum_constant_nodes')
    op.drop_index('ix_curriculum_constant_nodes_node_type', table_name='curriculum_constant_nodes')
    op.drop_table('curriculum_constant_nodes')
    # ### end Alembic commands ###
