"""add_user_permissions_table

Revision ID: 634d7645dec6
Revises: 2f3ac63f4728
Create Date: 2026-05-10 14:05:39.495718

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634d7645dec6'
down_revision: str | None = '2f3ac63f4728'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_edit_curriculum_constant_nodes', sa.Boolean(), nullable=False),
    sa.Column('can_edit_curriculum_folder_nodes', sa.Boolean(), nullable=False),
    sa.Column('can_create_yaml_template', sa.Boolean(), nullable=False),
    sa.Column('can_create_yaml_instance', sa.Boolean(), nullable=False),
    sa.Column('can_create_legacy_yaml_instance', sa.Boolean(), nullable=False),
    sa.Column('can_run_pipeline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_permissions_user_id')
    )
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    existing_indexes = {idx.get('name') for idx in inspector.get_indexes('curriculum_constant_nodes')}
    existing_uniques = {
        uq.get('name')
        for uq in inspector.get_unique_constraints('curriculum_constant_nodes')
        if uq.get('name')
    }

    if op.f('ix_curriculum_nodes_node_type') in existing_indexes:
        op.drop_index(op.f('ix_curriculum_nodes_node_type'), table_name='curriculum_constant_nodes')
    if op.f('ix_curriculum_nodes_parent_id') in existing_indexes:
        op.drop_index(op.f('ix_curriculum_nodes_parent_id'), table_name='curriculum_constant_nodes')
    if op.f('ix_curriculum_nodes_path') in existing_indexes:
        op.drop_index(op.f('ix_curriculum_nodes_path'), table_name='curriculum_constant_nodes')

    if op.f('uq_curriculum_nodes_parent_slug') in existing_uniques:
        op.drop_constraint(op.f('uq_curriculum_nodes_parent_slug'), 'curriculum_constant_nodes', type_='unique')
    if op.f('uq_curriculum_nodes_path') in existing_uniques:
        op.drop_constraint(op.f('uq_curriculum_nodes_path'), 'curriculum_constant_nodes', type_='unique')
    if 'ix_curriculum_constant_nodes_node_type' not in existing_indexes:
        op.create_index('ix_curriculum_constant_nodes_node_type', 'curriculum_constant_nodes', ['node_type'], unique=False)
    if 'ix_curriculum_constant_nodes_parent_id' not in existing_indexes:
        op.create_index('ix_curriculum_constant_nodes_parent_id', 'curriculum_constant_nodes', ['parent_id'], unique=False)
    if 'ix_curriculum_constant_nodes_path' not in existing_indexes:
        op.create_index('ix_curriculum_constant_nodes_path', 'curriculum_constant_nodes', ['path'], unique=False)

    if 'uq_curriculum_constant_nodes_parent_slug' not in existing_uniques:
        op.create_unique_constraint('uq_curriculum_constant_nodes_parent_slug', 'curriculum_constant_nodes', ['parent_id', 'slug'])
    if 'uq_curriculum_constant_nodes_path' not in existing_uniques:
        op.create_unique_constraint('uq_curriculum_constant_nodes_path', 'curriculum_constant_nodes', ['path'])
    if bind.dialect.name != 'sqlite':
        op.alter_column('property_definitions', 'defined_at_curriculum_node_id',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Text(),
                   existing_nullable=False)
        op.alter_column('property_definitions', 'label',
                   existing_type=sa.TEXT(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_definitions', 'label',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('property_definitions', 'defined_at_curriculum_node_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint('uq_curriculum_constant_nodes_path', 'curriculum_constant_nodes', type_='unique')
    op.drop_constraint('uq_curriculum_constant_nodes_parent_slug', 'curriculum_constant_nodes', type_='unique')
    op.drop_index('ix_curriculum_constant_nodes_path', table_name='curriculum_constant_nodes')
    op.drop_index('ix_curriculum_constant_nodes_parent_id', table_name='curriculum_constant_nodes')
    op.drop_index('ix_curriculum_constant_nodes_node_type', table_name='curriculum_constant_nodes')
    op.create_unique_constraint(op.f('uq_curriculum_nodes_path'), 'curriculum_constant_nodes', ['path'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_curriculum_nodes_parent_slug'), 'curriculum_constant_nodes', ['parent_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_curriculum_nodes_path'), 'curriculum_constant_nodes', ['path'], unique=False)
    op.create_index(op.f('ix_curriculum_nodes_parent_id'), 'curriculum_constant_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_curriculum_nodes_node_type'), 'curriculum_constant_nodes', ['node_type'], unique=False)
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
